name: Release Application

on:
  workflow_call:

jobs:
  release-ai:
    name: Release AI App
    runs-on: ubuntu-22.04
    env:
      PROJECT_NAME: courserecom
      APP_NAME: ai
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Azure CLI Login
        uses: azure/login@v3
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID_TERRAFORM }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy AI to Container App
        uses: azure/cli@v3
        with:
          azcliversion: latest
          inlineScript: |
            az containerapp update \
              -n ca-${{ env.PROJECT_NAME }}-${{ env.APP_NAME }} \
              -g rg-${{ env.PROJECT_NAME }} \
              --image acr${{ env.PROJECT_NAME }}.azurecr.io/${{ env.APP_NAME }}:latest \
              --set-env-vars \
                TIMESTAMP=$(date +%s) \

